# C1 - Greater-Turkic
code: C1
name: Greater-Turkic

patronymic_suffixes:
  "oğlu": son of
  "kızı": daughter of
  "o'g'li": son of
  qizi: daughter of
  ogly: son of
  gyzy: daughter of
  uulu: son of
  kyzy: daughter of
  "ұлы": son of
  "қызы": daughter of
