# C4 - Arabic Gulf
code: C4
name: Arabic Gulf

patronymic_patterns:
  ibn: son of
  "ابن": son of
  bin: son of
  "بن": son of
  bint: daughter of
  "بنت": daughter of
  abu: father of
  "أبو": father of
  um: mother of
  "أم": mother of
  umm: mother of

family_prefixes:
  - Al
  - "آل"
  - Aal
  - Bani
  - "بني"
  - Banu
  - "بنو"
