# E4 - Korea
code: E4
name: Korea

titles:
  # Korean
  - 교수
  - 부교수
  - 조교수
  - 강사
  - 연구원
  - 박사
  - 석사
  - 학사
  - 선생님
  - 선생
  - 의사
  - 변호사
  # English
  - Prof
  - Dr
  - Mr
  - Mrs
  - Ms
  - Professor
  - Doctor

common_surnames:
  - 김
  - 이
  - 박
  - 최
  - 정
  - 강
  - 조
  - 윤
  - 장
  - 임
  - 한
  - 오
  - 서
  - 신
  - 권
  - 황
  - 안
  - 송
  - 류
  - 전
  - 홍
  - 고
  - 문
  - 양
  - 손
  - 배
  - 백
  - 허
  - 유
  - 남
  - 심
  - 노
  - 하
  - 곽
  - 성
  - 차
  - 주
  - 우
  - 구
  - 나
  - 민
  - 진
  - 지
  - 엄
