FROM python:3.12-slim

# Install system deps
RUN apt-get update && apt-get install -y \
    build-essential \
    automake \
    libtool \
    pkg-config

# Copy requirements
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "pynini==2.1.6.post1"

# Copy application
COPY . /app
WORKDIR /app

# Build FSTs
RUN python src/v5/generate_tables.py
RUN python src/v5/fst_helpers.py

CMD ["python", "-m", "gmnap.server"]