#!/usr/bin/env python3
"""
Diagnose the concurrent processing GlobalID collision issue.
"""

import sys
import hashlib
import threading
import time
from collections import defaultdict

sys.path.insert(0, "src")

from gmnap.core.globalid import generate_global_id_from_entry
from gmnap.core.pipeline import GMNAPPipeline
from gmnap.core.database import GMNAPDatabase


def test_globalid_generation():
    """Test if GlobalIDs are unique for different names."""
    print("=== Testing GlobalID Generation ===")

    test_entries = []
    globalids = set()
    duplicates = []

    # Generate test entries
    for i in range(20):
        entry = {
            "CanonicalLatin": f"TestName{i}, TestGiven{i}",
            "CanonicalNative": f"TestName{i}, TestGiven{i}",  # Same as Latin for test
        }
        test_entries.append(entry)

        # Generate GlobalID
        global_id = generate_global_id_from_entry(entry)

        if global_id in globalids:
            duplicates.append((i, entry, global_id))
        else:
            globalids.add(global_id)

        print(f"Entry {i}: {entry['CanonicalLatin'][:30]} -> {global_id}")

    print(f"\nUnique GlobalIDs: {len(globalids)}/{len(test_entries)}")
    if duplicates:
        print(f"❌ Found {len(duplicates)} duplicates!")
        for idx, entry, gid in duplicates:
            print(f"  Entry {idx}: {entry['CanonicalLatin']} -> {gid}")
    else:
        print("✅ All GlobalIDs are unique")

    return test_entries


def test_pipeline_processing(test_entries):
    """Test pipeline processing without concurrency."""
    print("\n=== Testing Pipeline Processing (Sequential) ===")

    pipeline = GMNAPPipeline({"database_path": "test_sequential.db"})

    processed_globalids = set()
    duplicates = []

    for i, entry in enumerate(test_entries):
        try:
            processed = pipeline.process_entry(entry.copy())
            global_id = processed["GlobalID"]

            if global_id in processed_globalids:
                duplicates.append((i, entry, global_id))
            else:
                processed_globalids.add(global_id)

            print(f"Processed {i}: {global_id}")
        except Exception as e:
            print(f"Failed to process entry {i}: {e}")

    print(
        f"\nProcessed unique GlobalIDs: {len(processed_globalids)}/{len(test_entries)}"
    )
    if duplicates:
        print(f"❌ Found {len(duplicates)} duplicates in pipeline!")

    # Check database
    stats = pipeline.database.get_stats()
    print(f"Database entries: {stats['total_entries']}")

    return processed_globalids


def test_concurrent_processing():
    """Test concurrent processing to reproduce the issue."""
    print("\n=== Testing Concurrent Processing ===")

    pipeline = GMNAPPipeline({"database_path": "test_concurrent.db"})

    # Track GlobalIDs generated by each thread
    thread_globalids = defaultdict(list)
    lock = threading.Lock()

    def process_batch(thread_id, start_idx, count):
        """Process a batch of entries in a thread."""
        for i in range(start_idx, start_idx + count):
            entry = {
                "CanonicalLatin": f"Thread{thread_id}_Name{i}, Given{i}",
                "TerritoryCode": "US",  # Force A1 region
            }

            try:
                processed = pipeline.process_entry(entry)
                global_id = processed["GlobalID"]

                with lock:
                    thread_globalids[thread_id].append((i, global_id))

            except Exception as e:
                print(f"Thread {thread_id} failed on entry {i}: {e}")

    # Launch threads
    threads = []
    num_threads = 5
    entries_per_thread = 20

    start_time = time.time()

    for t in range(num_threads):
        thread = threading.Thread(
            target=process_batch, args=(t, t * entries_per_thread, entries_per_thread)
        )
        threads.append(thread)
        thread.start()

    # Wait for completion
    for thread in threads:
        thread.join()

    elapsed = time.time() - start_time

    # Analyze results
    all_globalids = []
    for thread_id, ids in thread_globalids.items():
        all_globalids.extend(ids)
        print(f"Thread {thread_id}: Generated {len(ids)} GlobalIDs")

    # Check for duplicates across threads
    globalid_set = set()
    cross_thread_duplicates = []

    for idx, gid in all_globalids:
        if gid in globalid_set:
            cross_thread_duplicates.append((idx, gid))
        else:
            globalid_set.add(gid)

    print(f"\nTotal GlobalIDs generated: {len(all_globalids)}")
    print(f"Unique GlobalIDs: {len(globalid_set)}")
    print(f"Cross-thread duplicates: {len(cross_thread_duplicates)}")

    # Check database
    stats = pipeline.database.get_stats()
    print(f"Database entries: {stats['total_entries']}")
    print(f"Expected entries: {num_threads * entries_per_thread}")

    if stats["total_entries"] < num_threads * entries_per_thread:
        print(
            f"❌ Missing {num_threads * entries_per_thread - stats['total_entries']} entries!"
        )
    else:
        print("✅ All entries persisted")

    print(f"\nProcessing time: {elapsed:.2f}s")
    print(f"Throughput: {len(all_globalids) / elapsed:.1f} entries/sec")


def check_region_assignment():
    """Check if region assignment might be causing issues."""
    print("\n=== Testing Region Assignment ===")

    pipeline = GMNAPPipeline()

    test_cases = [
        {"CanonicalLatin": "Test, Name"},  # No region specified
        {"CanonicalLatin": "Test, Name", "TerritoryCode": "US"},  # US -> A1
        {"CanonicalLatin": "Test, Name", "RegionCode": "A1"},  # Explicit A1
    ]

    for i, entry in enumerate(test_cases):
        processed = pipeline.process_entry(entry.copy())
        print(f"Case {i}: {entry} -> Region: {processed.get('RegionCode')}")


if __name__ == "__main__":
    # Clean up test databases
    import os

    for db in ["test_sequential.db", "test_concurrent.db"]:
        if os.path.exists(db):
            os.remove(db)

    # Run diagnostics
    test_entries = test_globalid_generation()
    test_pipeline_processing(test_entries[:10])  # Test subset
    test_concurrent_processing()
    check_region_assignment()

    # Clean up
    for db in ["test_sequential.db", "test_concurrent.db"]:
        if os.path.exists(db):
            os.remove(db)
