import pytest

#!/usr/bin/env python3
"""
Test surname pattern detection directly.
"""

# Surname patterns from manager.py
SURNAME_PATTERNS = {
    "A1": {
        "smith",
        "johnson",
        "williams",
        "jones",
        "brown",
        "davis",
        "miller",
        "wilson",
        "moore",
        "taylor",
        "anderson",
        "thomas",
        "jackson",
        "white",
        "harris",
        "martin",
        "thompson",
        "garcia",
        "martinez",
        "robinson",
        "clark",
        "rodriguez",
        "lewis",
        "lee",
        "walker",
        "hall",
        "allen",
        "young",
        "king",
        "wright",
        "scott",
        "green",
        "baker",
        "adams",
        "nelson",
        "mitchell",
        "campbell",
        "carter",
        "roberts",
        "phillips",
        "turner",
        "williams",
        "parker",
        "murphy",
        "cook",
        "rogers",
        "morgan",
        "peterson",
        "bailey",
        "reed",
        "stewart",
        "morris",
        "watson",
        "sanders",
        "newton",
        "hamilton",
        "turing",
        "shannon",
        "church",
        "hardy",
        "russell",
    },
    "B1": {
        "ivanov",
        "petrov",
        "sidorov",
        "smirnov",
        "volkov",
        "kuznetsov",
        "popov",
        "sokolov",
        "lebedev",
        "kozlov",
        "novikov",
        "morozov",
        "vasiliev",
        "fedorov",
        "mikhailov",
        "kovalenko",
        "bondarenko",
        "tkachenko",
        "kravchenko",
        "shevchenko",
        # Real mathematician surnames
        "agranovich",
        "akhiezer",
        "aleksandrov",
        "andronov",
        "arnold",
        "aronszajn",
        "babenko",
        "bakalov",
        "bary",
        "baryshnikov",
        "bashkirov",
        "belyi",
        "berezansky",
        "bernstein",
        "besicovitch",
        "birman",
        "blashke",
        "bogolyubov",
        "bokhoven",
        "brahmanin",
        "bunyakovsky",
        "chebyshev",
        "chernoff",
        "cherny",
        "chernyshevsky",
        "daniil",
        "dmitriev",
        "dobrushin",
        "dynkin",
        "efimov",
        "egorov",
        "faddeev",
        "feller",
        "fomin",
        "fréchet",
        "gelfand",
        "gelfond",
        "glivenko",
        "gnedenko",
        "gromov",
        "kantorovich",
        "karpelevich",
        "khinchin",
        "khintchine",
        "kolmogorov",
        "kolmogorova",
        "krasovskii",
        "krein",
        "krylov",
        "kurosh",
        "landau",
        "lavrentiev",
        "linnik",
        "luzin",
        "lyapunov",
        "mal'tsev",
        "mandelstam",
        "markov",
        "menshov",
        "milman",
        "novikov",
        "ostrogradsky",
        "pavlov",
        "pavlovsky",
        "perelman",
        "petrovsky",
        "pontryagin",
        "prokhorov",
        "pyatetskii-shapiro",
        "rokhlin",
        "ryzhik",
        "sazonov",
        "shnirelman",
        "shor",
        "sinai",
        "skorokhod",
        "smirnov",
        "sobolev",
        "steklov",
        "stepanov",
        "stieltjes",
        "tikhonov",
        "urysohn",
        "vinogradov",
        "vishik",
        "voronoi",
        "yaglom",
        "zeldovich",
        "zolotarev",
    },
    "B2": {
        "kowalski",
        "nowak",
        "wiśniewski",
        "wójcik",
        "kowalczyk",
        "kamiński",
        "lewandowski",
        "zieliński",
        "szymański",
        "woźniak",
        "dąbrowski",
        "kozłowski",
        "jankowski",
        "wojciechowski",
        "kwiatkowski",
        "mazur",
        "krawczyk",
        "kaczmarek",
        "piotrowski",
        "banach",
        "sierpiński",
        "tarski",
        "zygmund",
        "steinhaus",
        "ulam",
        "mazurkiewicz",
        "kuratowski",
    },
    "E1": {
        "wang",
        "li",
        "zhang",
        "liu",
        "chen",
        "yang",
        "zhao",
        "huang",
        "zhou",
        "wu",
        "xu",
        "sun",
        "ma",
        "zhu",
        "hu",
        "guo",
        "lin",
        "he",
        "luo",
        "gao",
        "zheng",
        "liang",
        "xie",
        "song",
        "tang",
        "deng",
        "han",
        "feng",
        "dong",
        "yu",
        "fu",
        "cao",
        "wei",
        "shen",
        "peng",
        "lu",
        "su",
        "jiang",
        "cai",
        "jia",
        "ding",
        "xia",
        "ye",
        "pan",
        "yao",
        "yuan",
        "tian",
        "qian",
        "shi",
        # Real mathematician surnames from YAML
        "an",
        "bao",
        "cai",
        "cao",
        "chan",
        "chang",
        "chao",
        "cheang",
        "chen",
        "cheng",
        "cheung",
        "chew",
        "chiang",
        "chiu",
        "choi",
        "choo",
        "chow",
        "chu",
        "dai",
        "deng",
        "ding",
        "dong",
        "fang",
        "feng",
        "fu",
        "gao",
        "geng",
        "gu",
        "guo",
        "han",
        "he",
        "hu",
        "huang",
        "jiang",
        "ju",
        "li",
        "lin",
        "liu",
        "lu",
        "lü",
        "ma",
        "ng",
        "qian",
        "qu",
        "shao",
        "shen",
        "shu",
        "su",
        "sun",
        "tang",
        "tse",
        "tsui",
        "tu",
        "wang",
        "wong",
        "wu",
        "xie",
        "xu",
        "yan",
        "yang",
        "yao",
        "yeo",
        "yu",
        "yuen",
        "ze",
        "zhai",
        "zhang",
        "zhao",
        "zheng",
        "zhou",
        "zhu",
        "zhun",
        "zhuo",
        "zou",
        "zun",
        "zuo",
    },
    "E4": {
        "kim",
        "lee",
        "park",
        "choi",
        "jung",
        "kang",
        "cho",
        "yoon",
        "jang",
        "lim",
        "han",
        "oh",
        "seo",
        "shin",
        "kwon",
        "hwang",
        "ahn",
        "song",
        "hong",
        "moon",
        "yang",
        "bae",
        "ko",
        "son",
    },
}

# Test names
test_names = [
    ("Newton, Isaac", "newton", "A1"),
    ("Sierpiński, Wacław", "sierpiński", "B2"),
    ("Wang, Xiaoming", "wang", "E1"),
    ("Kim, Min-su", "kim", "E4"),
    ("Chebyshev, Pafnuty", "chebyshev", "B1"),
    ("Erdős, Paul", "erdős", None),  # Hungarian, not in patterns
]


def extract_family_name(name: str) -> str:
    """Extract family name from 'Family, Given' format."""
    if ", " in name:
        return name.split(", ")[0].strip().lower()
    return name.strip().lower()


@pytest.mark.timeout(15)
def test_surname_patterns():
    """Test if surnames are being detected correctly."""

    print("Testing surname pattern detection...\n")

    for name, expected_surname, expected_region in test_names:
        family_name = extract_family_name(name)

        print(f"Name: {name}")
        print(f"  Extracted surname: {family_name}")
        print(f"  Expected: {expected_surname}")

        # Check which regions have this surname
        found_in = []
        for region, surnames in SURNAME_PATTERNS.items():
            if family_name in surnames:
                found_in.append(region)

        if found_in:
            print(f"  Found in regions: {', '.join(found_in)}")
            if expected_region and expected_region in found_in:
                print(f"  PASS Correctly found in {expected_region}")
            else:
                print(f"  FAIL Expected {expected_region}, found in {found_in}")
        else:
            print("  FAIL Not found in any region patterns")

        print()


if __name__ == "__main__":
    test_surname_patterns()
