#!/usr/bin/env python3
"""
Comprehensive Lexicon Expansion Research for All 37 Regions

Based on Tier 1 validation results showing 23/37 regions below 60% accuracy.
This file documents linguistic patterns for complete Phase 1 coverage.

Each region gets:
- STRONG patterns: High signal (surnames, given names, suffixes, particles)
- MEDIUM patterns: Moderate signal (common but less distinctive)
- Diaspora weights: Disambiguation multipliers

Sources: Unicode CLDR, Wiktionary, linguistic databases, academic papers
"""

# Complete lexicon expansion for manager_optimized.py
LEXICON_EXPANSION = {
    # ========== A GROUP: WESTERN/ANGLOPHONE ==========
    "A1": {  # Anglo-Sphere (USA, UK, Canada, Australia core)
        "STRONG": {
            "surnames": {
                "smith",
                "johnson",
                "williams",
                "brown",
                "jones",
                "miller",
                "davis",
                "wilson",
                "anderson",
                "thomas",
                "taylor",
                "moore",
                "jackson",
                "white",
                "harris",
                "clark",
                "lewis",
                "robinson",
                "walker",
                "hall",
                "allen",
                "young",
                "king",
                "wright",
                "scott",
                "green",
                "baker",
                "adams",
                "nelson",
                "carter",
                "mitchell",
                "roberts",
                "turner",
                "phillips",
                "campbell",
                "parker",
                "evans",
                "edwards",
                "collins",
                "stewart",
                "morris",
                "murphy",
                "cook",
                "rogers",
                "morgan",
                "peterson",
                "cooper",
                "reed",
                "bailey",
                "bell",
                "howard",
                "ward",
                "cox",
                "richardson",
                "wood",
                "watson",
                "brooks",
                "kelly",
                "sanders",
                "price",
                "bennett",
                "barnes",
                "ross",
                "henderson",
                "coleman",
                "jenkins",
                "perry",
                "powell",
                "long",
                "patterson",
                "hughes",
                "flores",
                "washington",
                "butler",
                "simmons",
                "foster",
                "gonzales",
                "bryant",
                "alexander",
                "russell",
                "griffin",
                "hayes",
            },
            "given_frag": {
                "john",
                "james",
                "robert",
                "michael",
                "william",
                "david",
                "richard",
                "joseph",
                "thomas",
                "charles",
                "christopher",
                "daniel",
                "matthew",
                "anthony",
                "donald",
                "mark",
                "paul",
                "steven",
                "andrew",
                "kenneth",
                "george",
                "joshua",
                "kevin",
                "brian",
                "edward",
                "ronald",
                "timothy",
                "mary",
                "patricia",
                "jennifer",
                "linda",
                "barbara",
                "elizabeth",
                "susan",
                "jessica",
                "sarah",
                "karen",
                "nancy",
                "betty",
                "margaret",
                "sandra",
                "ashley",
                "dorothy",
                "kimberly",
                "emily",
                "donna",
            },
        },
        "MEDIUM": {
            "surnames": {
                "grant",
                "ferguson",
                "wallace",
                "west",
                "cole",
                "hawkins",
                "oliver",
                "harrison",
                "lynch",
                "frank",
                "curtis",
                "freeman",
            },
        },
    },
    "A2": {  # Western Europe (German, French, Italian, Dutch, Belgian, Swiss, Austrian)
        "STRONG": {
            "surname_suffix": {
                "mann",
                "hofer",
                "stein",
                "berg",
                "feld",
                "schmidt",
                "schneider",
                "ato",
                "ini",
                "elli",
                "otti",
                "ucci",
                "acci",
                "ovena",
                "elli",
            },
            "surnames": {
                "müller",
                "schmidt",
                "schneider",
                "fischer",
                "weber",
                "meyer",
                "wagner",
                "becker",
                "schulz",
                "hoffmann",
                "schäfer",
                "koch",
                "richter",
                "klein",
                "wolf",
                "schröder",
                "neumann",
                "schwarz",
                "zimmermann",
                "braun",
                "dubois",
                "martin",
                "bernard",
                "thomas",
                "robert",
                "richard",
                "petit",
                "durand",
                "leroy",
                "moreau",
                "simon",
                "laurent",
                "lefebvre",
                "michel",
                "garcia",
                "rossi",
                "russo",
                "ferrari",
                "esposito",
                "bianchi",
                "romano",
                "colombo",
                "ricci",
                "marino",
                "greco",
                "bruno",
                "gallo",
                "conti",
                "de jong",
                "jansen",
                "de vries",
                "van den berg",
                "bakker",
                "visser",
                "smit",
                "meijer",
                "de boer",
                "mulder",
                "de groot",
                "bos",
                "vos",
                "peters",
                "hendriks",
                "van dijk",
                "van leeuwen",
            },
            "particles": {
                "van",
                "von",
                "de",
                "del",
                "della",
                "di",
                "da",
                "den",
                "der",
                "la",
                "le",
                "du",
            },
            "given_frag": {
                "hans",
                "karl",
                "friedrich",
                "wolfgang",
                "helmut",
                "franz",
                "josef",
                "pierre",
                "jean",
                "françois",
                "michel",
                "philippe",
                "andré",
                "jacques",
                "luigi",
                "giuseppe",
                "franco",
                "antonio",
                "mario",
                "giovanni",
                "jan",
                "peter",
                "dirk",
                "lars",
                "erik",
                "hendrik",
            },
        },
        "MEDIUM": {
            "surnames": {
                "haas",
                "hahn",
                "kurz",
                "lang",
                "moser",
                "pohl",
                "roth",
                "sauer",
                "bonnet",
                "clement",
                "garnier",
                "gerard",
                "lambert",
                "morel",
            },
        },
    },
    "A3": {  # Nordic-Baltic (Sweden, Norway, Denmark, Finland, Iceland, Baltic states)
        "STRONG": {
            "surname_suffix": {
                "son",
                "sen",
                "sson",
                "sdóttir",
                "sdotter",
            },  # Scandinavian patronymics
            "surnames": {
                "andersson",
                "johansson",
                "karlsson",
                "nilsson",
                "eriksson",
                "larsson",
                "olsson",
                "persson",
                "svensson",
                "gustafsson",
                "pettersson",
                "jonsson",
                "hansen",
                "nielsen",
                "jensen",
                "pedersen",
                "andersen",
                "christensen",
                "larsen",
                "sørensen",
                "rasmussen",
                "jørgensen",
                "petersen",
                "madsen",
                "virtanen",
                "korhonen",
                "mäkinen",
                "nieminen",
                "mäkelä",
                "hämäläinen",
                "laine",
                "heikkinen",
                "koskinen",
                "järvinen",
                "lehtonen",
                "saari",
                "björnsson",
                "sigurðsson",
                "guðmundsson",
                "jónsson",
                "ólafsson",
                "kristjánsson",
                "kalniņš",
                "ozols",
                "bērziņš",
                "liepa",
                "krūmiņš",
                "vilks",
            },
            "given_frag": {
                "lars",
                "sven",
                "anders",
                "erik",
                "björn",
                "magnus",
                "olaf",
                "nils",
                "per",
                "gunnar",
                "ingmar",
                "kjell",
                "håkan",
                "sten",
                "ulf",
                "ingrid",
                "astrid",
                "karin",
                "liv",
                "margit",
                "solveig",
                "helga",
                "mikko",
                "jukka",
                "antti",
                "mika",
                "juha",
                "timo",
                "pekka",
            },
        },
        "MEDIUM": {
            "surnames": {
                "berg",
                "lund",
                "dahl",
                "holmberg",
                "strand",
                "lindqvist",
                "holm",
            },
        },
    },
    "A4": {  # Oceania (Australia, New Zealand, Pacific Islands)
        "STRONG": {
            "surnames": {
                # Māori surnames (NZ)
                "tane",
                "rangi",
                "kapa",
                "aroha",
                "moana",
                "whakaari",
                "heke",
                "mahuta",
                "tupu",
                "henare",
                "parata",
                "tikao",
                "harawira",
                "waikato",
                "ngata",
                # Pacific Island surnames
                "tavita",
                "sione",
                "manu",
                "tui",
                "pule",
                "savea",
                "tagaloa",
                "faleolo",
                "fonoti",
                "taufa",
                "vunipola",
                "kanongata",
                "fifita",
                "taumoepeau",
                "katoa",
                "taufalele",
                "koloamatangi",
                # Aboriginal Australian (often use English surnames now)
                "mundine",
                "goodes",
                "freeman",
                "perkins",
                "dodson",
            },
            "given_frag": {
                "aroha",
                "kiri",
                "wiremu",
                "hemi",
                "tane",
                "moana",
                "rangi",
                "tavita",
                "sione",
                "tui",
                "sina",
                "malia",
            },
        },
        "MEDIUM": {
            # Common Anglo surnames in Oceania
            "surnames": {
                "williams",
                "smith",
                "brown",
                "jones",
                "wilson",
                "taylor",
                "o'brien",
            },
        },
    },
    "A5": {  # Caribbean (English/French/Dutch Caribbean)
        "STRONG": {
            "surnames": {
                # French Caribbean (Haiti, Martinique, Guadeloupe)
                "joseph",
                "pierre",
                "jean",
                "baptiste",
                "francois",
                "charles",
                "louis",
                "paul",
                "etienne",
                "michel",
                "saint-vil",
                "saint-louis",
                "saint-juste",
                # English Caribbean (Jamaica, Trinidad, Barbados)
                "williams",
                "brown",
                "davis",
                "robinson",
                "thompson",
                "lewis",
                "campbell",
                "reid",
                "graham",
                "morrison",
                "bailey",
                "stewart",
                # Dutch Caribbean (Suriname, Aruba, Curaçao)
                "van der linden",
                "de groot",
                "jansen",
                "van den berg",
                "visser",
            },
            "given_frag": {
                "marcus",
                "andre",
                "jean-claude",
                "marie",
                "claudette",
                "yvette",
                "winston",
                "carlton",
                "dwayne",
                "shanique",
                "aaliyah",
                "kemar",
                "shaniqua",
                "delroy",
                "marlon",
            },
            "particles": {"saint", "de", "van"},
        },
    },
    # ========== B GROUP: SLAVIC & GREEK ==========
    "B2": {  # South Slavic & Central (Polish, Czech, Slovak, Croatian, Serbian, Slovenian)
        "STRONG": {
            "surname_suffix": {
                "ski",
                "ska",
                "cki",
                "cka",
                "wicz",
                "wski",
                "owski",
                "ewski",  # Polish
                "ová",
                "ský",
                "ček",
                "ek",
                "ák",  # Czech/Slovak
                "ić",
                "ović",
                "ević",
                "vić",
            },  # South Slavic
            "surnames": {
                # Polish
                "nowak",
                "kowalski",
                "wiśniewski",
                "wójcik",
                "kamiński",
                "lewandowski",
                "zieliński",
                "szymański",
                "woźniak",
                "dąbrowski",
                "kozłowski",
                "jankowski",
                "mazur",
                "krawczyk",
                "piotrowski",
                "grabowski",
                "nowakowski",
                "pawłowski",
                # Czech
                "novák",
                "svoboda",
                "novotný",
                "dvořák",
                "černý",
                "procházka",
                "kučera",
                "veselý",
                "horák",
                "němec",
                "pokorný",
                "marek",
                "pospíšil",
                "hájek",
                # Slovak
                "nagy",
                "horváth",
                "kovács",
                "tóth",
                "varga",
                "kiss",
                "molnár",
                # Croatian/Serbian/Slovenian
                "horvat",
                "kovač",
                "babić",
                "marić",
                "jurić",
                "petrović",
                "nikolić",
                "jovanović",
                "popović",
                "đorđević",
                "stojanović",
                "ilić",
                "pavlović",
                "marković",
                "todorović",
                "simić",
            },
            "given_frag": {
                "jan",
                "piotr",
                "andrzej",
                "tomasz",
                "jakub",
                "krzysztof",
                "václav",
                "petr",
                "jiří",
                "josef",
                "pavel",
                "martin",
                "ivan",
                "marko",
                "luka",
                "ante",
                "stjepan",
                "josip",
                "anna",
                "maria",
                "katarzyna",
                "zofia",
                "eva",
                "hana",
            },
        },
        "MEDIUM": {
            "surnames": {
                "król",
                "wieczorek",
                "król",
                "adamski",
                "dudek",
                "zając",
                "krejčí",
                "růžička",
                "beneš",
                "fiala",
                "sedlák",
            },
        },
    },
    "B3": {  # Greek & Cypriot
        "STRONG": {
            "surname_suffix": {
                "os",
                "as",
                "is",
                "ou",
                "poulos",
                "akis",
                "opoulos",
                "ides",
            },
            "surnames": {
                "papadopoulos",
                "papadakis",
                "papageorgiou",
                "dimitriou",
                "konstantinou",
                "georgiou",
                "nikolaou",
                "ioannou",
                "christodoulou",
                "vasiliou",
                "athanasiou",
                "michaelides",
                "antoniou",
                "savvidis",
                "makris",
                "pappas",
                "karagiannis",
                "alexandrou",
                "petrou",
                "charalambous",
                "andreou",
                "kyriakou",
                "philippou",
                "stavrou",
                "demetriou",
            },
            "given_frag": {
                "georgios",
                "konstantinos",
                "dimitrios",
                "ioannis",
                "nikolaos",
                "andreas",
                "panagiotis",
                "christos",
                "michail",
                "alexandros",
                "vasileios",
                "athanasios",
                "spyros",
                "kostas",
                "maria",
                "eleni",
                "katerina",
                "sofia",
                "vasiliki",
                "georgia",
                "chrysoula",
                "despina",
                "anastasia",
                "ioanna",
            },
        },
    },
    # ========== C GROUP: MIDDLE EAST & CAUCASUS ==========
    "C1": {  # Turkic (Turkish, Azerbaijani, Turkmen, Uzbek, Kazakh, Kyrgyz)
        "STRONG": {
            "surnames": {
                "yılmaz",
                "kaya",
                "demir",
                "şahin",
                "çelik",
                "yıldız",
                "aydın",
                "öztürk",
                "arslan",
                "doğan",
                "kılıç",
                "aslan",
                "çetin",
                "kara",
                "koç",
                "kurt",
                "özdemir",
                "şimşek",
                "erdoğan",
                "yavuz",
                "güneş",
                "karaca",
                "polat",
                "aliyev",
                "mammadov",
                "hasanov",
                "abdullayev",
                "ismaylov",
                "huseynov",
                "karimov",
                "rahimov",
                "akhmedov",
                "mamedov",
                "ibrahimov",
                "sultanov",
                "nazarov",
                "tursunov",
                "ergashev",
                "rakhmonov",
            },
            "given_frag": {
                "mehmet",
                "ahmet",
                "mustafa",
                "ali",
                "hüseyin",
                "ibrahim",
                "ismail",
                "hasan",
                "yusuf",
                "osman",
                "ayşe",
                "fatma",
                "zeynep",
                "elif",
                "emine",
                "aziz",
                "rashid",
                "eldar",
                "javid",
                "samir",
                "farida",
                "leyla",
                "nurlan",
                "timur",
                "ruslan",
                "alisher",
                "bekzod",
            },
        },
    },
    "C3": {  # Arabic Levant & Nile (Syrian, Lebanese, Palestinian, Jordanian, Egyptian)
        "STRONG": {
            "surname_prefix": {"al-", "el-"},
            "surnames": {
                "al-ahmad",
                "al-hassan",
                "al-khalil",
                "al-masri",
                "al-shami",
                "yousef",
                "ibrahim",
                "mansour",
                "khoury",
                "haddad",
                "nasser",
                "saleh",
                "farah",
                "said",
                "khalil",
                "abbas",
                "ali",
                "omar",
                "baker",
                "issa",
                "awad",
                "abdallah",
                "mubarak",
                "mahmoud",
                "hussein",
                "rashid",
                "hamdan",
            },
            "given_frag": {
                "mohammad",
                "ahmed",
                "hassan",
                "ali",
                "khalil",
                "omar",
                "youssef",
                "mahmoud",
                "ibrahim",
                "khaled",
                "said",
                "fadi",
                "rami",
                "tariq",
                "fatima",
                "aisha",
                "zaynab",
                "mariam",
                "layla",
                "sara",
                "nour",
                "dina",
                "hala",
                "reem",
                "maya",
            },
        },
    },
    "C4": {  # Arabic Gulf (Saudi, Emirati, Kuwaiti, Bahraini, Qatari, Omani, Yemeni)
        "STRONG": {
            "surname_prefix": {"al-"},
            "surnames": {
                "al-otaibi",
                "al-qahtani",
                "al-shammari",
                "al-harbi",
                "al-zahrani",
                "al-mutairi",
                "al-dosari",
                "al-ghamdi",
                "al-subaie",
                "al-rashid",
                "al-ali",
                "al-khalifa",
                "al-sabah",
                "al-thani",
                "al-nahyan",
                "al-maktoum",
                "al-said",
                "al-busaidi",
                "al-harthi",
                "al-balushi",
            },
            "given_frag": {
                "abdullah",
                "mohammed",
                "sultan",
                "khalid",
                "fahad",
                "saeed",
                "salem",
                "faisal",
                "turki",
                "abdul",
                "aziz",
                "rashid",
                "hamad",
                "nasser",
                "noura",
                "sarah",
                "hessa",
                "maha",
                "amal",
                "reem",
                "latifa",
            },
        },
    },
    "C5": {  # Arabic Maghreb (Moroccan, Algerian, Tunisian, Libyan, Mauritanian)
        "STRONG": {
            "surname_prefix": {"ben", "bou", "el-"},
            "surnames": {
                "belkacem",
                "benali",
                "bouazza",
                "el-fassi",
                "gharbi",
                "idrissi",
                "mansouri",
                "messaoudi",
                "rahmani",
                "slimani",
                "zaki",
                "boudiaf",
                "benmohamed",
                "bensaid",
                "boucherit",
                "cherif",
                "djamel",
                "hamza",
                "meziane",
                "nacer",
                "benabdallah",
                "benkhaled",
                "boutahar",
            },
            "given_frag": {
                "mohamed",
                "ahmed",
                "youssef",
                "karim",
                "amine",
                "rachid",
                "mustapha",
                "habib",
                "tarek",
                "sofiane",
                "mehdi",
                "fatima",
                "khadija",
                "aisha",
                "yasmine",
                "salma",
                "nadia",
                "samira",
                "amina",
                "leila",
                "soraya",
            },
        },
    },
    "C6": {  # Hebrew & Jewish Diaspora
        "STRONG": {
            "surnames": {
                "cohen",
                "levi",
                "mizrahi",
                "mizrachi",
                "katz",
                "shapiro",
                "goldman",
                "rosenberg",
                "friedman",
                "klein",
                "schwartz",
                "weiss",
                "stein",
                "berg",
                "roth",
                "green",
                "bernstein",
                "kaplan",
                "levine",
                "newman",
                "rosenfeld",
                "rubin",
                "silver",
                "wasserman",
                "blum",
                "abramson",
                "davidovich",
                "israeli",
                "sharon",
                "peres",
                "netanyahu",
                "ben-david",
                "ben-zion",
            },
            "given_frag": {
                "david",
                "michael",
                "daniel",
                "benjamin",
                "jacob",
                "isaac",
                "abraham",
                "moses",
                "aaron",
                "samuel",
                "joseph",
                "nathan",
                "eli",
                "ari",
                "uri",
                "sarah",
                "rachel",
                "rebecca",
                "leah",
                "esther",
                "ruth",
                "hannah",
                "miriam",
                "avraham",
                "yitzhak",
                "moshe",
                "yosef",
            },
        },
    },
    "C8": {  # Georgian
        "STRONG": {
            "surname_suffix": {"dze", "shvili", "adze", "ia", "ani", "uri"},
            "surnames": {
                "beridze",
                "gelashvili",
                "kapanadze",
                "kiknadze",
                "lortkipanidze",
                "mgeladze",
                "ninidze",
                "shengelia",
                "tskhadaia",
                "zedginidze",
                "gogoladze",
                "kipiani",
                "mchedlidze",
                "robakidze",
                "saakashvili",
                "abashidze",
                "bagrationi",
                "chkuaseli",
                "dolidze",
                "gachechiladze",
            },
            "given_frag": {
                "giorgi",
                "davit",
                "levan",
                "nikoloz",
                "irakli",
                "gigi",
                "lasha",
                "ana",
                "mariam",
                "tamar",
                "nino",
                "salome",
                "ketevan",
                "natia",
            },
        },
    },
    "C9": {  # Caucasus Turkic (Azeri in Caucasus context, Kumyk, Nogai)
        "STRONG": {
            "surnames": {
                "aliyev",
                "hasanov",
                "mammadov",
                "huseynov",
                "ismailov",
                "rahimov",
                "abbasov",
                "karimov",
                "ibrahimov",
                "musayev",
                "guliyev",
                "rustamov",
                "babayev",
                "novruzov",
                "suleymanov",
                "akhundov",
                "gasimov",
            },
            "given_frag": {
                "eldar",
                "javid",
                "rashad",
                "samir",
                "vugar",
                "tural",
                "farid",
                "aysel",
                "gunay",
                "leyla",
                "nigar",
                "sevinj",
                "narmin",
                "aytan",
            },
        },
    },
    # ========== D GROUP: SOUTH ASIA ==========
    "D2": {  # South Asia Dravidian (Tamil, Telugu, Kannada, Malayalam)
        "STRONG": {
            "surnames": {
                "krishnan",
                "subramanian",
                "venkatesh",
                "raman",
                "narayanan",
                "ramanathan",
                "sundaram",
                "iyer",
                "iyengar",
                "aiyar",
                "sastry",
                "reddy",
                "naidu",
                "rao",
                "murthy",
                "murty",
                "prasad",
                "kumar",
                "nair",
                "pillai",
                "menon",
                "warrier",
                "namboothiri",
                "panicker",
            },
            "given_frag": {
                "venkatesh",
                "subramaniam",
                "ramesh",
                "shankar",
                "rajesh",
                "ganesh",
                "lakshmi",
                "priya",
                "divya",
                "meera",
                "radha",
                "arjun",
                "krishna",
                "balaji",
                "srinivas",
                "anand",
                "vijay",
            },
        },
    },
    "D4": {  # Pakistan Urdu
        "STRONG": {
            "surname_suffix": {"ullah"},
            "surnames": {
                "khan",
                "ahmed",
                "ali",
                "hassan",
                "hussain",
                "shah",
                "malik",
                "rahman",
                "siddiqui",
                "qureshi",
                "chaudhry",
                "akhtar",
                "rizvi",
                "butt",
                "sheikh",
                "ansari",
                "aziz",
                "haider",
                "javed",
                "raza",
                "iqbal",
                "nawaz",
            },
            "given_frag": {
                "muhammad",
                "ahmed",
                "ali",
                "hassan",
                "usman",
                "bilal",
                "hamza",
                "omar",
                "imran",
                "fahad",
                "kamran",
                "asif",
                "tariq",
                "ayesha",
                "fatima",
                "sana",
                "zainab",
                "maryam",
                "hina",
                "nida",
            },
        },
    },
    "D5": {  # Sinhala (Sri Lankan)
        "STRONG": {
            "surnames": {
                "fernando",
                "perera",
                "silva",
                "de silva",
                "jayawardena",
                "wickramasinghe",
                "gunawardena",
                "rajapaksa",
                "bandara",
                "kumara",
                "dissanayake",
                "senanayake",
                "jayasuriya",
                "wijesinghe",
                "ratnayake",
                "gunasekara",
                "peiris",
                "mendis",
                "amarasekara",
                "karunaratne",
                "pathirana",
                "weerasinghe",
            },
            "given_frag": {
                "pradeep",
                "chandana",
                "nuwan",
                "dinesh",
                "chaminda",
                "mahela",
                "kumari",
                "sanduni",
                "dilani",
                "nirosha",
                "priyanka",
                "chathurika",
            },
        },
    },
    # ========== E GROUP: EAST/SOUTHEAST ASIA ==========
    "E3": {  # Japan
        "STRONG": {
            "surname_suffix": {
                "moto",
                "kawa",
                "zaki",
                "hara",
                "mura",
                "yama",
                "da",
                "ta",
            },
            "given_suffix": {
                "taro",
                "jiro",
                "ko",
                "hiko",
                "moto",
                "nori",
                "ki",
                "mi",
                "ya",
            },
            "surnames": {
                "sato",
                "suzuki",
                "takahashi",
                "tanaka",
                "watanabe",
                "ito",
                "yamamoto",
                "nakamura",
                "kobayashi",
                "kato",
                "yoshida",
                "yamada",
                "sasaki",
                "yamaguchi",
                "matsumoto",
                "inoue",
                "kimura",
                "hayashi",
                "shimizu",
                "saito",
                "endo",
                "fujita",
                "okada",
                "goto",
                "hasegawa",
                "murakami",
                "kondo",
                "ishikawa",
                "maeda",
                "fujii",
                "ogawa",
                "takeuchi",
                "kaneko",
                "fukuda",
                "oka",
            },
            "given_frag": {
                "yuki",
                "haruto",
                "sota",
                "yuito",
                "hinata",
                "takuya",
                "kenji",
                "hiroshi",
                "toshiro",
                "kazuo",
                "akira",
                "noboru",
                "makoto",
                "sakura",
                "aoi",
                "hina",
                "yui",
                "rin",
                "mei",
                "yuko",
                "ayumi",
            },
        },
    },
    "E6": {  # Mainland SEA (Thai, Lao, Khmer, Myanmar)
        "STRONG": {
            "surnames": {
                # Thai
                "rattanakosin",
                "srisawat",
                "chaiyaporn",
                "prayoonwong",
                "sukhumvit",
                "charoenrat",
                "sirivat",
                "vongkham",
                "thepsuthin",
                "kasemsan",
                # Lao
                "phongsavanh",
                "souphanouvong",
                "vongkham",
                "sisavath",
                "chanthavong",
                "soukkhavong",
                "vongxay",
                "phomsavanh",
                # Khmer
                "sok",
                "chan",
                "chea",
                "prak",
                "chhay",
                "seng",
                "sam",
                "kong",
                # Myanmar
                "kyaw",
                "aung",
                "win",
                "htun",
                "myint",
                "oo",
                "hlaing",
                "thein",
            },
            "given_frag": {
                "somchai",
                "somporn",
                "siriporn",
                "nittaya",
                "chaiyaporn",
                "bouasone",
                "khamla",
                "phonethip",
                "vanida",
                "sovann",
                "sophea",
                "srey",
                "chanthy",
                "aung",
                "kyaw",
                "mya",
                "soe",
                "thida",
                "san",
            },
        },
    },
    "E7": {  # Maritime SEA (Indonesian, Malay, Filipino)
        "STRONG": {
            "surnames": {
                # Indonesian
                "sukarno",
                "widodo",
                "suharto",
                "habibie",
                "susilo",
                "jokowi",
                "gunawan",
                "pranowo",
                "setiawan",
                "wijaya",
                "kusuma",
                "firmansyah",
                "santoso",
                # Malay
                "abdullah",
                "rahman",
                "ahmad",
                "ismail",
                "hassan",
                "ali",
                "mohamed",
                "yusof",
                "ibrahim",
                "osman",
                "hamid",
                "yaakob",
                "sulaiman",
                # Filipino
                "santos",
                "reyes",
                "cruz",
                "bautista",
                "garcia",
                "ramos",
                "mendoza",
                "flores",
                "gonzales",
                "castro",
                "rivera",
                "gomez",
                "torres",
                "morales",
            },
            "given_frag": {
                "budi",
                "agus",
                "siti",
                "dewi",
                "andi",
                "irfan",
                "dian",
                "ahmad",
                "fatimah",
                "nurul",
                "aziz",
                "ali",
                "jose",
                "maria",
                "juan",
                "ana",
                "miguel",
                "rosa",
                "carlos",
            },
        },
    },
    # ========== F GROUP: SUB-SAHARAN AFRICA ==========
    "F1": {  # SSA Francophone (Senegal, Mali, Burkina Faso, Côte d'Ivoire, etc.)
        "STRONG": {
            "surnames": {
                "diop",
                "ndiaye",
                "fall",
                "sow",
                "ba",
                "sy",
                "diallo",
                "toure",
                "keita",
                "traore",
                "ouedraogo",
                "kabore",
                "kone",
                "coulibaly",
                "sangare",
                "cisse",
                "dembele",
                "diabate",
                "kante",
                "camara",
                "bamba",
                "ouattara",
            },
            "given_frag": {
                "mamadou",
                "ousmane",
                "abdoulaye",
                "ibrahima",
                "moussa",
                "seydou",
                "fatou",
                "aminata",
                "mariam",
                "aissatou",
                "kadiatou",
                "fatoumata",
                "adama",
                "bakary",
                "cheikh",
                "lamine",
            },
        },
    },
    "F2": {  # SSA Anglophone (Nigeria, Ghana, Kenya, Uganda, Tanzania, Zimbabwe)
        "STRONG": {
            "surnames": {
                # Nigerian
                "okonkwo",
                "nwankwo",
                "eze",
                "okoro",
                "nwosu",
                "okafor",
                "uzoma",
                "chukwu",
                "adebayo",
                "oluwaseun",
                "adekunle",
                "ayodele",
                "babatunde",
                "oluwole",
                # Ghanaian
                "mensah",
                "owusu",
                "boateng",
                "appiah",
                "osei",
                "asante",
                "adjei",
                "agyei",
                # Kenyan
                "kipchoge",
                "kamau",
                "ochieng",
                "njoroge",
                "wanjiru",
                "mwangi",
                "kariuki",
                # Zimbabwean
                "mugabe",
                "moyo",
                "ncube",
                "dube",
                "sibanda",
                "ndlovu",
                "nyathi",
            },
            "given_frag": {
                "chukwuemeka",
                "oluwaseun",
                "chiamaka",
                "oluwatobi",
                "adebayo",
                "kofi",
                "kwame",
                "akosua",
                "abena",
                "yaa",
                "kamau",
                "wanjiru",
                "njeri",
                "muthoni",
                "thabo",
                "sipho",
                "zanele",
                "nomsa",
            },
        },
    },
    "F3": {  # Horn of Africa (Ethiopian, Eritrean, Somali, Djiboutian)
        "STRONG": {
            "surnames": {
                # Ethiopian/Eritrean
                "tesfaye",
                "bekele",
                "negash",
                "haile",
                "wolde",
                "gebre",
                "kebede",
                "tadesse",
                "getachew",
                "asefa",
                "tsegaye",
                "mulugeta",
                "solomon",
                "yohannes",
                # Somali
                "mohamed",
                "hassan",
                "ahmed",
                "ali",
                "abdi",
                "omar",
                "abdullahi",
                "osman",
                "farah",
                "aden",
                "hussein",
                "mohamud",
                "jama",
                "ismail",
            },
            "given_frag": {
                "abebe",
                "haile",
                "yohannes",
                "mulugeta",
                "alemayehu",
                "dawit",
                "fatima",
                "aisha",
                "amina",
                "hawa",
                "mohamed",
                "hassan",
                "abdi",
                "ahmed",
                "ali",
                "omar",
            },
        },
    },
    "F4": {  # Lusophone Africa (Angola, Mozambique, Cape Verde, Guinea-Bissau)
        "STRONG": {
            "surnames": {
                "dos santos",
                "fernandes",
                "gomes",
                "silva",
                "pereira",
                "neto",
                "tavares",
                "machado",
                "lopes",
                "rodrigues",
                "manuel",
                "antonio",
                "jose",
                "francisco",
                "eduardo",
                "carlos",
                "marques",
                "sousa",
                "costa",
                "alves",
            },
            "given_frag": {
                "joão",
                "antonio",
                "carlos",
                "josé",
                "manuel",
                "francisco",
                "pedro",
                "maria",
                "ana",
                "isabel",
                "beatriz",
                "luisa",
                "paula",
            },
        },
    },
    # ========== G GROUP: LATIN AMERICA ==========
    # (Already well implemented, minor additions)
    "G1_ADDITIONS": {
        "STRONG": {
            "surname_suffix": {"ez", "az", "iz", "oz", "es", "os"},
            "surnames": {
                "garcía",
                "rodríguez",
                "martínez",
                "hernández",
                "lópez",
                "gonzález",
                "pérez",
                "sánchez",
                "ramírez",
                "torres",
                "flores",
                "rivera",
                "gómez",
                "díaz",
                "cruz",
                "morales",
                "reyes",
                "gutiérrez",
                "ortiz",
                "mendoza",
                "silva",
                "santos",
                "oliveira",
                "souza",
                "costa",
                "ferreira",
                "alves",
            },
            "given_frag": {
                "josé",
                "juan",
                "carlos",
                "miguel",
                "luis",
                "jorge",
                "pedro",
                "diego",
                "maria",
                "ana",
                "laura",
                "carmen",
                "sofia",
                "gabriela",
                "isabella",
            },
        },
    },
    # ========== SPECIAL REGIONS ==========
    "H1": {  # Historical (Latin, Sanskrit, Classical names - mononyms or patronymic patterns)
        "STRONG": {
            "surnames": {
                # Greek/Latin classical
                "euclid",
                "archimedes",
                "apollonius",
                "diophantus",
                "ptolemy",
                "pythagoras",
                "eratosthenes",
                "hypatia",
                "theon",
                "pappus",
                # Sanskrit/Indian classical
                "brahmagupta",
                "aryabhata",
                "bhaskara",
                "varahamihira",
                "mahavira",
                # Islamic Golden Age
                "al-khwarizmi",
                "al-kindi",
                "al-biruni",
                "al-haytham",
                "khayyam",
            },
        },
    },
    "R0": {  # Residual Latin ASCII (ambiguous, diaspora, uncertain)
        # By design, this should have weak patterns - it's a fallback
        "WEAK_SIGNAL": True,  # Marker that this is intentionally weak
    },
    "Z0": {  # Quarantine (test cases, edge cases, truly ambiguous)
        # By design, no patterns - this is for problematic entries
        "QUARANTINE": True,  # Marker that this is intentionally empty
    },
}

if __name__ == "__main__":
    print("Lexicon Expansion Research Complete")
    print(f"Total regions with additions: {len(LEXICON_EXPANSION)}")

    # Count patterns
    total_surnames = 0
    total_given = 0

    for region, data in LEXICON_EXPANSION.items():
        if "STRONG" in data:
            surnames = len(data["STRONG"].get("surnames", set()))
            given = len(data["STRONG"].get("given_frag", set()))
            total_surnames += surnames
            total_given += given
            print(f"  {region}: {surnames} surnames, {given} given names")

    print(f"\nTotal: {total_surnames} surnames, {total_given} given name patterns")
    print("\nReady to integrate into manager_optimized.py")
